---

http:
  bind_addr: 0.0.0.0:80
  keep_alive_secs: 75
  max_body_size_mb: 32
  workers: 48
log_path: /var/log/nexus-cognitron/{{ ENV_TYPE }}
search_engine:
  auto_commit: false
  data_path: /nexus-cognitron/summa
  default_page_size: 5
  timeout_secs: 15
  writer_memory_mb: 1024
  writer_threads: 4
