---
services:
  nexus-cognitron-web:
    depends_on:
      - nexus-meta-api-envoy
    environment:
      ENV_TYPE: production
      NEXUS_COGNITRON_WEB_application.address: 0.0.0.0
      NEXUS_COGNITRON_WEB_application.port: 3000
      NEXUS_COGNITRON_WEB_ipfs.gateway.url: https://cloudflare-ipfs.com
      NEXUS_COGNITRON_WEB_meta_api.url: http://localhost:8080
    image: thesuperpirate/nexus-cognitron-web:latest
    ports:
      - '3000:3000'
  nexus-meta-api:
    depends_on:
      - summa
    environment:
      ENV_TYPE: production
      NEXUS_META_API_grpc.address: '0.0.0.0'
      NEXUS_META_API_grpc.port: 9090
      NEXUS_META_API_summa.url: 'http://summa:8082'
    image: thesuperpirate/nexus-meta-api:latest
  nexus-meta-api-envoy:
    depends_on:
      - nexus-meta-api
    image: envoyproxy/envoy-dev:latest
    ports:
      - '8080:8080'
    volumes:
      - './envoy.yaml:/etc/envoy/envoy.yaml'
  summa:
    environment:
      ENV_TYPE: production
      SUMMA_debug: 'true'
      SUMMA_http.address: '0.0.0.0'
      SUMMA_http.port: '8082'
    image: izihawa/summa:latest
    volumes:
      - '${DATA_PATH}:/summa/data'
version: "3"
