---

promotions:
  - texts:
      en: 🎁 Help us at /donate to accelerate knowledge unchaining
    weight: 3.0
  - texts:
      en: ⤴️ Stay tuned with us at {related_channel}
      es: ⤴️ Mantente en contacto con nosotros en {related_channel}
      it: ⤴️ Resta aggiornato con noi su {related_channel}
      pb: ⤴️ Fique ligado conosco em {related_channel}
      ru: ⤴️ Оставайся на связи с нами на {related_channel}
    weight: 1.0
